# kronicle_sdk/conf/env_keys.py
KRONICLE_HOST = "KRONICLE_HOST"
KRONICLE_PORT = "KRONICLE_PORT"
KRONICLE_USR_NAME = "KRONICLE_USR_NAME"
KRONICLE_USR_PASS = "KRONICLE_USR_PASS"  # nosec B105
KRONICLE_SU_NAME = "KRONICLE_SU_NAME"
KRONICLE_SU_PASS = "KRONICLE_SU_PASS"  # nosec B105
