[tox]
min_version = 4.0
envlist = py310, py311, py312, py313, py314, bandit, flake8

[testenv:bandit]
description = run bandit security linter
basepython = python3
deps = bandit
commands = bandit -c pyproject.toml -r src

[testenv:flake8]
description = run flake8 linter
basepython = python3
deps = flake8
commands = flake8 src

[testenv]
description = run pytest with all dev dependencies
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/src
passenv =
    KRONICLE_HOST
    KRONICLE_PORT
    KRONICLE_USR_NAME
    KRONICLE_USR_PASS
    KRONICLE_SU_NAME
    KRONICLE_SU_PASS
deps =
    -r requirements.txt
    -r requirements-dev.txt

commands = pytest
